Repository jupyterlab/lumino, pull requests merged in 2021-12, with the labels that each got.

#268 Fix transposed display names for arrow keys
  packages/commands/src/index.ts
Labels: bug

#270 Automated Changelog Entry for 2021.12.13 on main
  CHANGELOG.md
Labels: documentation

#272 Update references to main branch (`master` → `main`)
  README.md
  binder/README.md
  docs/source/conf.py
Labels: maintenance

#275 fix(DockPanel): Drag and Drop fails when hosted in a ShadowRoot
  package.json
  packages/dragdrop/src/index.ts
  packages/widgets/src/dockpanel.ts
Labels: enhancement

#276 fix(TabBar): Event forwarding fails when hosted in a ShadowRoot
  packages/widgets/src/docklayout.ts
  packages/widgets/src/dockpanel.ts
  packages/widgets/src/tabbar.ts
  packages/widgets/src/tabpanel.ts
Labels: enhancement

#277 Prevent opening an empty menu
  examples/example-dockpanel/src/index.ts
  packages/widgets/src/menubar.ts
  packages/widgets/tests/src/menubar.spec.ts
Labels: bug
