Repository jupyterlab/lumino, pull requests merged in 2021-09, with the labels that each got.

#226 Add binder configuration
  .github/jupyterlab-probot.yml
  binder/README.md
  binder/environment.yaml
  binder/postBuild
  binder/start
Labels: maintenance

#229 Add binder link to Readme
  README.md
Labels: maintenance

#232 Class and aria attribute must be changed on title
  packages/widgets/src/accordionpanel.ts
Labels: bug

#234 Add screencasts and examples to the README
  README.md
Labels: documentation

#237 Remove deprecated MediaStreamErrorEvent
  packages/virtualdom/src/index.ts
  review/api/virtualdom.api.md
Labels: bug

#238 Automated Changelog Entry for 2021.9.22 on master
  CHANGELOG.md
Labels: documentation

#239 Optimise grid rendering
  packages/datagrid/src/datagrid.ts
Labels: maintenance

#241 Add static examples in docs
  .github/jupyterlab-probot.yml
  .gitignore
  CONTRIBUTING.md
  docs/source/conf.py
  docs/source/examples.rst
  docs/source/index.rst
  examples/example-accordionpanel/index.html
  examples/example-dockpanel/index.html
  package.json
  packages/algorithm/tdoptions.json
  packages/application/tdoptions.json
  packages/collections/tdoptions.json
  packages/commands/tdoptions.json
  packages/coreutils/tdoptions.json
  packages/datagrid/tdoptions.json
  packages/datastore/tdoptions.json
  packages/disposable/tdoptions.json
  packages/domutils/tdoptions.json
  packages/dragdrop/tdoptions.json
  packages/keyboard/tdoptions.json
  packages/messaging/tdoptions.json
  packages/polling/tdoptions.json
  packages/properties/tdoptions.json
  packages/signaling/tdoptions.json
  packages/virtualdom/tdoptions.json
  packages/widgets/tdoptions.json
  typedoc.js
Labels: documentation

#123 Basic Touch Events
  README.md
  packages/dragdrop/src/index.ts
  packages/widgets/src/dockpanel.ts
  packages/widgets/src/tabbar.ts
  packages/widgets/style/tabbar.css
Labels: enhancement

#243 Automated Changelog Entry for 2021.9.30 on master
  CHANGELOG.md
Labels: documentation
