Repository jupyterlab/lumino, pull requests merged in 2021-07, with the labels that each got.

#199 Automated Changelog Entry for 2021.7.19 on master
  CHANGELOG.md
Labels: documentation

#201 Automated Changelog Entry for 2021.7.19 on master
  CHANGELOG.md
Labels: documentation

#203 Don't sort context menu item by selector
  packages/widgets/src/contextmenu.ts
  packages/widgets/tests/src/contextmenu.spec.ts
  packages/widgets/tests/src/index.spec.ts
Labels: enhancement

#204 Automated Changelog Entry for 2021.7.21 on master
  CHANGELOG.md
Labels: documentation

#206 Add option to not group context menu item by target
  packages/widgets/src/contextmenu.ts
  packages/widgets/tests/src/contextmenu.spec.ts
Labels: enhancement

#208 Added option to force items' position
  packages/widgets/src/menubar.ts
Labels: enhancement

#209 Automated Changelog Entry for 2017.7.22 on master
  CHANGELOG.md
Labels: documentation

#210 Fixes for Check Release
  .github/workflows/tests.yml
  package.json
Labels: maintenance

#211 Automated Changelog Entry for 2021.7.23 on master
  CHANGELOG.md
Labels: documentation

#212 Remove Errant Changelog Entry
  CHANGELOG.md
Labels: documentation

#187 Make focus consistent with active element in menus
  packages/widgets/src/menu.ts
  packages/widgets/src/menubar.ts
Labels: maintenance
