Repository jupyterlab/lumino, pull requests merged in 2021-05, with the labels that each got.

#179 Fix selection mode
  packages/datagrid/src/basicmousehandler.ts
Labels: bug

#108 Implement plus button on TabBar
  examples/example-dockpanel/src/index.ts
  packages/default-theme/style/tabbar.css
  packages/widgets/src/dockpanel.ts
  packages/widgets/src/tabbar.ts
  packages/widgets/src/tabpanel.ts
  packages/widgets/style/tabbar.css
  packages/widgets/tests/src/tabbar.spec.ts
Labels: enhancement

#184 Add changelog entry for 2021.5.10
  CHANGELOG.md
Labels: documentation

#185 Fix changelog formatting for 2021-5-10 entry
  CHANGELOG.md
Labels: documentation

#124 Cell merging
  examples/example-datagrid/src/index.ts
  packages/datagrid/src/basicmousehandler.ts
  packages/datagrid/src/celleditor.ts
  packages/datagrid/src/celleditorcontroller.ts
  packages/datagrid/src/cellgroup.ts
  packages/datagrid/src/datagrid.ts
  packages/datagrid/src/datamodel.ts
  packages/datagrid/src/index.ts
Labels: enhancement
