Repository jupyterlab/lumino, pull requests merged in 2021-08, with the labels that each got.

#214 Automated Changelog Entry for 2021.8.3 on master
  CHANGELOG.md
Labels: documentation

#216 Fix handling of pip cache in CI
  .github/workflows/tests.yml
Labels: maintenance

#217 Update dependencies
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-datastore/package.json
  examples/example-dockpanel/package.json
  package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/datastore/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
  yarn.lock
Labels: maintenance

#218 New renderer: HyperlinkRenderer
  examples/example-datagrid/src/index.ts
  packages/datagrid/src/basicmousehandler.ts
  packages/datagrid/src/hyperlinkrenderer.ts
  packages/datagrid/src/index.ts
Labels: enhancement

#219 Automated Changelog Entry for 2021.8.12 on master
  CHANGELOG.md
Labels: documentation

#220 Update release notes
  RELEASE.md
Labels: documentation

#222 Use Check Links Action
  .github/workflows/tests.yml
  package.json
Labels: maintenance

#223 Add 'padding' argument to fitColumnNames function
  packages/datagrid/src/datagrid.ts
Labels: enhancement

#224 Automated Changelog Entry for 2021.8.23 on master
  CHANGELOG.md
Labels: documentation
