Repository jupyterlab/lumino, pull requests merged in 2022-10, with the labels that each got.

#425 Add deprecation warnings
  packages/collections/src/bplustree.ts
  packages/dragdrop/src/index.ts
Labels: maintenance

#428 Revert "Backport PR #395 on branch 1.x (Switch to using `setTimeout` for all deferred processing.)"
  packages/polling/src/poll.ts
Labels: bug

#430 Automated Changelog Entry for 2022.10.5 on 1.x
  CHANGELOG.md
Labels: documentation

#431 Fix minor code scan warnings
  packages/datagrid/src/datagrid.ts
  packages/widgets/src/commandpalette.ts
  packages/widgets/tests/src/widget.spec.ts
Labels: maintenance

#421 Add DockLayout tests
  packages/widgets/tests/src/docklayout.spec.ts
Labels: maintenance

#433 Add support for list of keystrokes
  packages/commands/src/index.ts
  packages/commands/tests/src/index.spec.ts
  packages/widgets/src/commandpalette.ts
  packages/widgets/src/menu.ts
  review/api/commands.api.md
Labels: enhancement

#437 Clean up test workflow
  .github/workflows/tests.yml
  package.json
Labels: maintenance

#438 Backport PR #432 on branch 1.x (Avoid menu layout trashing by moving DOM queries)
  packages/virtualdom/src/index.ts
  packages/widgets/src/contextmenu.ts
  packages/widgets/src/menu.ts
  packages/widgets/src/menubar.ts
  packages/widgets/tests/src/menu.spec.ts
  review/api/widgets.api.md
Labels: bug, performance

#441 Backport PR #433 on branch 1.x (Add support for list of keystrokes)
  packages/commands/src/index.ts
  packages/commands/tests/src/index.spec.ts
  packages/widgets/src/commandpalette.ts
  packages/widgets/src/menu.ts
Labels: enhancement

#440 Backport PR #322 on branch 1.x (Add `describedBy` to command)
  packages/commands/src/index.ts
  packages/commands/tests/src/index.spec.ts
Labels: enhancement

#439 Backport PR #373 on branch 1.x (Fix tab trap in menubar)
  README.md
  packages/widgets/src/menubar.ts
  packages/widgets/tests/src/menubar.spec.ts
Labels: enhancement, accessibility

#442 Backport PR #419 on branch 1.x (Add plugin description)
  packages/application/package.json
  packages/application/src/index.ts
  packages/application/tests/src/index.spec.ts
  packages/application/tests/tsconfig.json
Labels: enhancement

#402 Handle deferred processing when `document` is hidden
  packages/messaging/src/index.ts
  packages/messaging/tests/src/index.spec.ts
  packages/polling/src/poll.ts
  packages/polling/tests/src/poll.spec.ts
  review/api/polling.api.md
Labels: bug, enhancement, performance

#443 Add blocking signal feature
  packages/signaling/package.json
  packages/signaling/src/index.ts
  packages/signaling/tests/src/index.spec.ts
  review/api/signaling.api.md
Labels: enhancement

#444 Backport PR #443 on branch 1.x (Add blocking signal feature)
  packages/signaling/package.json
  packages/signaling/src/index.ts
  packages/signaling/tests/src/index.spec.ts
  review/api/signaling.api.md
Labels: enhancement

#446 Datagrid: Do not prevent page scroll if we are not actually scrolling the grid
  packages/datagrid/src/basicmousehandler.ts
  packages/datagrid/src/datagrid.ts
Labels: bug

#452 Update versions
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-datastore/package.json
  examples/example-dockpanel/package.json
  packages/application/package.json
  packages/commands/package.json
  packages/datagrid/package.json
  packages/datastore/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/dragdrop/package.json
  packages/polling/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: maintenance

#453 Automated Changelog Entry for 2022.10.31 on 1.x
  CHANGELOG.md
Labels: documentation
