Repository jupyterlab/lumino, pull requests merged in 2022-07, with the labels that each got.

#308 [memory-leak] Title.changed not cleared when owner is disposed
  packages/widgets/src/title.ts
  packages/widgets/src/widget.ts
  packages/widgets/tests/src/title.spec.ts
  packages/widgets/tests/src/widget.spec.ts
Labels: bug

#311 Update versions
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-datastore/package.json
  examples/example-dockpanel/package.json
  packages/application/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/widgets/package.json
Labels: maintenance

#317 Automated Changelog Entry for 2022.7.21 on main
  CHANGELOG.md
Labels: documentation

#323 Update my name and email
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/datastore/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: documentation

#324 Backport PR #323 on branch 1.x (Update my name and email)
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/datastore/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: documentation
