Repository jupyterlab/lumino, pull requests merged in 2022-08, with the labels that each got.

#321 Add `collapse` and `expand` methods to `AccordionPanel`
  packages/widgets/src/accordionpanel.ts
  packages/widgets/tests/src/accordionpanel.spec.ts
Labels: enhancement

#326 Backport PR #321 on branch 1.x (Add `collapse` and `expand` methods to `AccordionPanel`)
  packages/widgets/src/accordionpanel.ts
  packages/widgets/tests/src/accordionpanel.spec.ts
Labels: enhancement

#327 Remove mouse event handlers from SplitPanel
  packages/widgets/src/splitpanel.ts
  packages/widgets/tests/src/splitpanel.spec.ts
Labels: maintenance

#331 Allow describedBy to be an async function
  packages/commands/src/index.ts
  packages/commands/tests/src/index.spec.ts
Labels: enhancement

#335 Update versions
  .github/workflows/tests.yml
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-datastore/package.json
  examples/example-dockpanel/package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/datastore/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: maintenance

#337 Automated Changelog Entry for 2022.8.8 on 1.x
  CHANGELOG.md
Labels: documentation

#338 Automated Changelog Entry Forward Ported from v2022.8.8
  CHANGELOG.md
Labels: documentation

#342 Update NPM package author to Project Jupyter
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: documentation, maintenance

#345 Remove `BPlusTree` class from `@lumino/collections`
  packages/collections/src/bplustree.ts
  packages/collections/src/index.ts
Labels: maintenance

#350 Add more safety workflows
  .github/codeql/codeql-config.yml
  .github/dependabot.yml
  .github/workflows/auto-author-assign.yml
  .github/workflows/check-api-changes.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/license-header.yml
  .github/workflows/lock.yml
  .licenserc.yaml
  api-extractor-base.json
  review/api/algorithm.api.md
  review/api/application.api.md
  review/api/collections.api.md
  review/api/commands.api.md
  review/api/coreutils.api.md
  review/api/datagrid.api.md
  review/api/disposable.api.md
  review/api/dragdrop.api.md
  review/api/keyboard.api.md
  review/api/messaging.api.md
  review/api/polling.api.md
  review/api/properties.api.md
  review/api/signaling.api.md
  review/api/virtualdom.api.md
  review/api/widgets.api.md
Labels: maintenance

#354 Update and fix docs
  CHANGELOG.md
  docs/source/_templates/breadcrumbs.html
  docs/source/api_index.html
  docs/source/conf.py
  docs/source/index.rst
  package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
  tsconfigdoc.json
  typedoc.js
Labels: documentation

#355 Update `dragdrop` to use `PointerEvent` and `DragEvent`
  docs/source/migration.md
  packages/dragdrop/src/index.ts
  packages/dragdrop/tests/src/index.spec.ts
  packages/widgets/src/dockpanel.ts
  review/api/dragdrop.api.md
Labels: maintenance

#359 First Lumino 2 pre-release
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel-amd/package.json
  examples/example-dockpanel-iife/package.json
  examples/example-dockpanel/package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: maintenance

#365 Fix license header following 231f01c
  .licenserc.yaml
Labels: maintenance

#367 Automated Changelog Entry for 2022.8.22-alpha.0 on main
  CHANGELOG.md
Labels: documentation

#368 Fix documentation CI error
  docs/environment.yml
Labels: documentation

#369 Set npm tag to next for prerelease
  package.json
Labels: maintenance

#361 Refactor `retro()`, clean up iterators
  packages/algorithm/src/iter.ts
  packages/algorithm/src/retro.ts
  packages/algorithm/tests/src/iter.spec.ts
  packages/algorithm/tests/src/retro.spec.ts
  packages/collections/src/linkedlist.ts
Labels: bug, maintenance

#363 Update license copyright date
  LICENSE
Labels: documentation

#370 Bump to v2 alpha 1
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel-amd/package.json
  examples/example-dockpanel-iife/package.json
  examples/example-dockpanel/package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: maintenance

#371 Automated Changelog Entry for 2022.8.22-alpha.1 on main
  CHANGELOG.md
Labels: documentation

#373 Fix tab trap in menubar
  README.md
  packages/widgets/src/menubar.ts
  packages/widgets/tests/src/menubar.spec.ts
Labels: enhancement, accessibility

#376 Deprecate `each<T>(...)`
  docs/source/migration.md
  packages/algorithm/src/iter.ts
  packages/widgets/src/panellayout.ts
  packages/widgets/tests/src/accordionlayout.spec.ts
  packages/widgets/tests/src/boxlayout.spec.ts
  packages/widgets/tests/src/dockpanel.spec.ts
  packages/widgets/tests/src/panellayout.spec.ts
  packages/widgets/tests/src/splitlayout.spec.ts
  packages/widgets/tests/src/splitpanel.spec.ts
  packages/widgets/tests/src/stackedlayout.spec.ts
  packages/widgets/tests/src/tabbar.spec.ts
  packages/widgets/tests/src/tabpanel.spec.ts
  packages/widgets/tests/src/widget.spec.ts
  review/api/algorithm.api.md
Labels: documentation, maintenance

#378 Iterate on iterators
  docs/source/migration.md
  packages/algorithm/src/chain.ts
  packages/algorithm/src/empty.ts
  packages/algorithm/src/repeat.ts
  packages/algorithm/src/retro.ts
  packages/datagrid/src/basicselectionmodel.ts
  packages/widgets/src/docklayout.ts
  packages/widgets/src/dockpanel.ts
  packages/widgets/src/gridlayout.ts
  packages/widgets/src/panellayout.ts
  packages/widgets/src/singletonlayout.ts
  packages/widgets/src/widget.ts
  packages/widgets/tests/src/layout.spec.ts
  packages/widgets/tests/src/widget.spec.ts
  review/api/algorithm.api.md
Labels: documentation, maintenance

#377 Dynamic extensions reloading
  packages/application/src/index.ts
  packages/application/tests/src/index.spec.ts
  packages/application/tests/tsconfig.json
  packages/commands/src/index.ts
  review/api/application.api.md
Labels: enhancement

#380 Bump alpha versions
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel-amd/package.json
  examples/example-dockpanel-iife/package.json
  examples/example-dockpanel/package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: maintenance

#381 Automated Changelog Entry for 2022.8.29 on main
  CHANGELOG.md
Labels: documentation

#382 Fix service type
  .github/workflows/license-header.yml
  packages/application/src/index.ts
  review/api/application.api.md
Labels: bug

#383 Bump packages to v2-alpha.3
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel-amd/package.json
  examples/example-dockpanel-iife/package.json
  examples/example-dockpanel/package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: maintenance

#384 Automated Changelog Entry for 2022.8.30 on main
  CHANGELOG.md
Labels: documentation
