Repository jupyterlab/lumino, pull requests merged in 2022-01, with the labels that each got.

#279 chore(Widget): Simplify attach/detach sanity checking
  packages/widgets/src/widget.ts
Labels: enhancement

#280 Automated Changelog Entry for 2022.1.10 on main
  CHANGELOG.md
Labels: documentation

#281 fix(DockLayout): Invalid use of "this" in private namespace
  packages/widgets/src/docklayout.ts
Labels: bug

#283 Automated Changelog Entry for 2022.1.13 on main
  CHANGELOG.md
Labels: documentation

#285 Improve DockLayout code documentation
  packages/widgets/src/docklayout.ts
Labels: documentation
