Repository jupyterlab/lumino, pull requests merged in 2022-09, with the labels that each got.

#386 Make `Poll` an async iterable
  CHANGELOG.md
  packages/polling/README.md
  packages/polling/src/index.ts
  packages/polling/src/poll.ts
  packages/polling/tests/src/poll.spec.ts
  packages/polling/tests/tsconfig.json
  review/api/polling.api.md
Labels: enhancement

#388 Target ES2018
  .eslintrc.js
  docs/source/migration.md
  examples/example-accordionpanel/tsconfig.json
  examples/example-datagrid/tsconfig.json
  examples/example-dockpanel/tsconfig.json
  packages/algorithm/tests/tsconfig.json
  packages/algorithm/tsconfig.json
  packages/application/tests/tsconfig.json
  packages/application/tsconfig.json
  packages/collections/tests/tsconfig.json
  packages/collections/tsconfig.json
  packages/commands/tests/tsconfig.json
  packages/commands/tsconfig.json
  packages/coreutils/tests/tsconfig.json
  packages/coreutils/tsconfig.json
  packages/datagrid/tsconfig.json
  packages/disposable/tests/tsconfig.json
  packages/disposable/tsconfig.json
  packages/domutils/tests/tsconfig.json
  packages/domutils/tsconfig.json
  packages/dragdrop/tests/tsconfig.json
  packages/dragdrop/tsconfig.json
  packages/keyboard/tests/tsconfig.json
  packages/keyboard/tsconfig.json
  packages/messaging/tests/tsconfig.json
  packages/messaging/tsconfig.json
  packages/polling/README.md
  packages/polling/tsconfig.json
  packages/properties/tests/tsconfig.json
  packages/properties/tsconfig.json
  packages/signaling/tests/tsconfig.json
  packages/signaling/tsconfig.json
  packages/virtualdom/tests/tsconfig.json
  packages/virtualdom/tsconfig.json
  packages/widgets/tests/tsconfig.json
  packages/widgets/tsconfig.json
  tsconfigbase.json
Labels: maintenance, performance

#390 Use `pull_request_target` to have write access on fork
  .github/workflows/enforce-label.yml
  .github/workflows/license-header.yml
Labels: maintenance

#391 Fix bug that prevents any startup plugins from activating
  packages/application/src/index.ts
  packages/application/tests/src/index.spec.ts
Labels: bug

#393 Automated Changelog Entry for 2022.9.6 on main
  CHANGELOG.md
Labels: documentation

#396 Remove some webpack artifacts from `devDependencies`
  packages/dragdrop/package.json
  packages/widgets/package.json
  yarn.lock
Labels: dependencies, maintenance

#395 Switch to using `setTimeout` for all deferred processing.
  packages/polling/src/poll.ts
Labels: bug

#397 Backport PR #395 on branch 1.x (Switch to using `setTimeout` for all deferred processing.)
  CHANGELOG.md
  packages/polling/src/poll.ts
Labels: bug

#398 Update versions to v2 alpha.5
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel/package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: maintenance

#399 Automated Changelog Entry for 2022.9.9-alpha.5 on main
  CHANGELOG.md
Labels: documentation

#406 Improve title on accordion label
  packages/widgets/src/accordionpanel.ts
Labels: enhancement

#407 Fix labelledby to support multiple elements on page
  packages/widgets/src/accordionpanel.ts
  packages/widgets/src/tabbar.ts
  review/api/widgets.api.md
Labels: bug, accessibility

#408 Backport PR #406 on branch 1.x (Improve title on accordion label)
  packages/widgets/src/accordionpanel.ts
Labels: enhancement

#409 Backport PR #407 on branch 1.x (Fix labelledby to support multiple elements on page)
  packages/widgets/src/accordionpanel.ts
  packages/widgets/src/tabbar.ts
Labels: bug

#411 Fix resizing and mode switching in `DockPanel`
  examples/example-accordionpanel/index.html
  examples/example-datagrid/index.html
  examples/example-dockpanel-amd/index.html
  examples/example-dockpanel-iife/index.html
  examples/example-dockpanel/index.html
  packages/widgets/src/docklayout.ts
  packages/widgets/src/dockpanel.ts
  packages/widgets/tests/src/docklayout.spec.ts
  packages/widgets/tests/src/dockpanel.spec.ts
Labels: bug

#413 Bump packages to v2 alpha 6
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel-amd/package.json
  examples/example-dockpanel-iife/package.json
  examples/example-dockpanel/package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: maintenance

#414 Automated Changelog Entry for 2022.9.15-alpha.6 on main
  CHANGELOG.md
Labels: documentation

#415 Follow on to #411 addressing `yield*`
  docs/source/migration.md
  packages/algorithm/src/empty.ts
  packages/widgets/src/docklayout.ts
  review/api/algorithm.api.md
Labels: documentation, maintenance

#420 Add section to README: Learning Resources
  README.md
Labels: documentation

#394 Improve datagrid performance
  examples/example-datagrid/src/index.ts
  packages/datagrid/src/cellgroup.ts
  packages/datagrid/src/datagrid.ts
  review/api/datagrid.api.md
Labels: enhancement, performance

#419 Add plugin description
  packages/application/src/index.ts
  packages/application/tests/src/index.spec.ts
  review/api/application.api.md
Labels: enhancement

#422 Switch to pydata sphinx theme
  docs/environment.yml
  docs/source/conf.py
Labels: documentation

#416 Remove Internet Explorer from tests, add Webkit
  CONTRIBUTING.md
  package.json
  packages/algorithm/package.json
  packages/algorithm/tests/karma.conf.js
  packages/application/package.json
  packages/application/tests/karma.conf.js
  packages/collections/package.json
  packages/collections/tests/karma.conf.js
  packages/commands/package.json
  packages/commands/tests/karma.conf.js
  packages/coreutils/package.json
  packages/coreutils/tests/karma.conf.js
  packages/disposable/package.json
  packages/disposable/tests/karma.conf.js
  packages/domutils/package.json
  packages/domutils/tests/karma.conf.js
  packages/dragdrop/package.json
  packages/dragdrop/tests/karma.conf.js
  packages/keyboard/package.json
  packages/keyboard/tests/karma.conf.js
  packages/messaging/package.json
  packages/messaging/tests/karma.conf.js
  packages/polling/package.json
  packages/polling/tests/karma.conf.js
  packages/properties/package.json
  packages/properties/tests/karma.conf.js
  packages/signaling/package.json
  packages/signaling/tests/karma.conf.js
  packages/virtualdom/package.json
  packages/virtualdom/tests/karma.conf.js
  packages/widgets/package.json
  packages/widgets/tests/karma.conf.js
  yarn.lock
Labels: maintenance
