Repository jupyterlab/lumino, pull requests merged in 2022-11, with the labels that each got.

#459 Fix check release step
  package.json
Labels: maintenance

#455 Backport changelog for stable 1.x
  CHANGELOG.md
Labels: documentation

#451 Disable text eliding by default
  packages/datagrid/src/hyperlinkrenderer.ts
  packages/datagrid/src/textrenderer.ts
  review/api/datagrid.api.md
Labels: enhancement, performance

#462 Add async iterable `Stream` class that inherits from `Signal`
  packages/signaling/package.json
  packages/signaling/src/index.ts
  packages/signaling/tests/src/index.spec.ts
  review/api/signaling.api.md
Labels: enhancement

#464 When rejecting the internal promise in a `Stream`, catch failures
  packages/signaling/src/index.ts
Labels: bug

#458 Audit `DataGrid` public API in preparation for 0.x => 2.0
  .github/workflows/tests.yml
  .gitignore
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel-amd/package.json
  examples/example-dockpanel-iife/package.json
  examples/example-dockpanel/package.json
  notebooks/package.json
  packages/datagrid/package.json
  packages/datagrid/src/celleditor.ts
  packages/datagrid/src/notification.ts
  packages/default-theme/package.json
  packages/virtualdom/src/index.ts
  review/api/datagrid.api.md
  review/api/virtualdom.api.md
  yarn.lock
Labels: maintenance

#473 Fix drag-and-drop of nested dock panel
  examples/example-nested-dockpanel-amd/README.md
  examples/example-nested-dockpanel-amd/index.html
  examples/example-nested-dockpanel-amd/package.json
  examples/example-nested-dockpanel-amd/src/index.js
  examples/example-nested-dockpanel-amd/style/content.css
  examples/example-nested-dockpanel-amd/style/index.css
  examples/example-nested-dockpanel-amd/test/runner.js
  packages/widgets/src/dockpanel.ts
Labels: bug

#475 Backport PR #473 on branch 1.x (Fix drag-and-drop of nested dock panel)
  examples/example-nested-dockpanel-amd/README.md
  examples/example-nested-dockpanel-amd/index.html
  examples/example-nested-dockpanel-amd/package.json
  examples/example-nested-dockpanel-amd/src/index.js
  examples/example-nested-dockpanel-amd/style/content.css
  examples/example-nested-dockpanel-amd/style/index.css
  examples/example-nested-dockpanel-amd/test/runner.js
  packages/widgets/src/dockpanel.ts
Labels: bug

#474 Set up jupyter releaser
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  RELEASE.md
Labels: maintenance

#476 Backport #465 on branch 1.x (Improve the menubar accessibility)
  examples/example-menubar/index.html
  examples/example-menubar/package.json
  examples/example-menubar/src/index.ts
  examples/example-menubar/style/content.css
  examples/example-menubar/style/index.css
  examples/example-menubar/tsconfig.json
  examples/example-menubar/webpack.config.js
  packages/widgets/src/menubar.ts
  packages/widgets/tests/src/menubar.spec.ts
Labels: enhancement

#479 Correct example version for 1.x
  examples/example-nested-dockpanel-amd/package.json
Labels: maintenance

#480 Automated Changelog Entry for 2022.11.29 on 1.x
  CHANGELOG.md
Labels: documentation

#481 Use Firefox from playwright
  .github/workflows/tests.yml
  packages/algorithm/tests/karma.conf.js
  packages/application/tests/karma.conf.js
  packages/collections/tests/karma.conf.js
  packages/commands/tests/karma.conf.js
  packages/coreutils/tests/karma.conf.js
  packages/disposable/tests/karma.conf.js
  packages/domutils/tests/karma.conf.js
  packages/dragdrop/tests/karma.conf.js
  packages/keyboard/tests/karma.conf.js
  packages/messaging/tests/karma.conf.js
  packages/polling/tests/karma.conf.js
  packages/properties/tests/karma.conf.js
  packages/signaling/tests/karma.conf.js
  packages/virtualdom/tests/karma.conf.js
  packages/widgets/tests/karma.conf.js
Labels: maintenance
