Repository jupyterlab/lumino, pull requests merged in 2022-06, with the labels that each got.

#306 Enable bot PRs to auto-label
  .github/workflows/enforce-label.yml
Labels: maintenance

#304 Fix Accordion sizing issue
  packages/widgets/src/accordionpanel.ts
  packages/widgets/src/splitlayout.ts
  packages/widgets/src/splitpanel.ts
  packages/widgets/tests/src/accordionpanel.spec.ts
Labels: bug

#307 Automated Changelog Entry for 2022.6.7 on main
  CHANGELOG.md
Labels: documentation
