Repository jupyterlab/lumino, pull requests merged in 2022-12, with the labels that each got.

#484 Update documentation for Stream class
  packages/signaling/src/index.ts
  packages/signaling/tests/src/index.spec.ts
Labels: documentation

#485 Backport PR #377 on branch 1.x (Dynamic extensions reloading)
  packages/application/src/index.ts
  packages/application/tests/src/index.spec.ts
  packages/application/tests/tsconfig.json
Labels: enhancement

#486 Bump version
  CHANGELOG.md
  api-extractor-base.json
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-datastore/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  examples/example-nested-dockpanel-amd/package.json
  packages/application/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/widgets/package.json
  packages/widgets/src/menubar.ts
  review/api/algorithm.api.md
  review/api/application.api.md
  review/api/collections.api.md
  review/api/commands.api.md
  review/api/coreutils.api.md
  review/api/datagrid.api.md
  review/api/datastore.api.md
  review/api/disposable.api.md
  review/api/dragdrop.api.md
  review/api/keyboard.api.md
  review/api/polling.api.md
  review/api/virtualdom.api.md
  review/api/widgets.api.md
Labels: maintenance

#490 Fix finding dependents for deactivation
  packages/application/src/index.ts
Labels: bug

#494 Bump @lumino/application
  packages/application/package.json
Labels: maintenance

#495 Automated Changelog Entry for 2022.12.13 on 1.x
  CHANGELOG.md
Labels: documentation

#497 Add content-visibility hide mode
  packages/widgets/src/docklayout.ts
  packages/widgets/src/widget.ts
  packages/widgets/tests/src/widget.spec.ts
  review/api/widgets.api.md
Labels: enhancement

#500 Backport PR #497 on branch 1.x (Add content-visibility hide mode)
  packages/widgets/src/cssPatch.d.ts
  packages/widgets/src/docklayout.ts
  packages/widgets/src/widget.ts
  packages/widgets/tests/src/cssPatch.d.ts
  packages/widgets/tests/src/widget.spec.ts
  review/api/widgets.api.md
Labels: enhancement

#507 Accessibility: role attributes
  packages/widgets/src/accordionpanel.ts
  packages/widgets/src/commandpalette.ts
Labels: bug, accessibility
