Repository jupyterlab/lumino, pull requests merged in 2023-09, with the labels that each got.

#630 Datagrid: Introduce AsyncCellRenderer and ImageRenderer
  examples/example-datagrid/src/index.ts
  packages/datagrid/src/asynccellrenderer.ts
  packages/datagrid/src/datagrid.ts
  packages/datagrid/src/imagerenderer.ts
  packages/datagrid/src/index.ts
  packages/datagrid/tests/src/imagerenderer.spec.ts
  packages/datagrid/tests/src/index.spec.ts
  review/api/datagrid.api.md
Labels: enhancement, feature

#631 Added a test to check the add tab button has a role of button
  packages/widgets/tests/src/tabbar.spec.ts
Labels: maintenance

#607 MenuBar: do not focus on hover
  .github/workflows/tests.yml
  docs/source/conf.py
  docs/source/examples.rst
  packages/default-theme/style/menubar.css
  packages/widgets/src/menubar.ts
  packages/widgets/tests/src/menubar.spec.ts
  review/api/widgets.api.md
Labels: bug

#635 Keydown event at bubbling phase
  packages/application/src/index.ts
  review/api/application.api.md
Labels: enhancement, accessibility

#636 Update versions
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  packages/application/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/widgets/package.json
  yarn.lock
Labels: maintenance
