Repository jupyterlab/lumino, pull requests merged in 2023-03, with the labels that each got.

#549 Fix requiring position for `MenuBar` undetermined index
  packages/widgets/src/menubar.ts
Labels: bug

#550 Make `IOverflowMenuOptions.title` optional
  packages/widgets/src/menubar.ts
  packages/widgets/tests/src/menubar.spec.ts
  packages/widgets/tests/src/splitlayout.spec.ts
  review/api/widgets.api.md
Labels: enhancement

#551 Bump to 2.0.0-rc.1
  buildutils/package.json
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
  yarn.lock
Labels: maintenance

#556 Update version to 2.0.0 final
  RELEASE.md
  buildutils/package.json
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel-amd/package.json
  examples/example-dockpanel-iife/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  examples/example-nested-dockpanel-amd/package.json
  package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
  yarn.lock
Labels: maintenance

#557 Improve documentation
  CHANGELOG.md
  LICENSE
  docs/source/_static/switcher.json
  docs/source/conf.py
Labels: documentation

#558 Backport changelog from 1.x
  CHANGELOG.md
Labels: documentation

#560 Disable size containment for split handle
  packages/widgets/src/splitlayout.ts
Labels: bug

#563 Prevents enter from being interpreted as emoji
  examples/example-menubar/src/index.ts
  packages/commands/src/index.ts
Labels: bug

#561 Remove `IDragEvent` deprecated tag
  packages/dragdrop/src/index.ts
Labels: bug, documentation

#565 Update versions
  .gitignore
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-datastore/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  packages/application/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/dragdrop/package.json
  packages/widgets/package.json
Labels: maintenance

#567 Automated Changelog Entry for 2023.3.27-0 on 1.x
  CHANGELOG.md
Labels: documentation

#566 Update versions
  CHANGELOG.md
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  packages/application/package.json
  packages/commands/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/widgets/package.json
  yarn.lock
Labels: maintenance
