Repository jupyterlab/lumino, pull requests merged in 2023-10, with the labels that each got.

#643 Switch from `hub` to `gh` CLI
  .github/workflows/license-header.yml
Labels: maintenance

#651 Add default top/left for `.lm-mod-drag-image`
  packages/dragdrop/style/index.css
Labels: bug

#652 Propagate scroll from backdrop
  packages/dragdrop/src/index.ts
  packages/dragdrop/style/index.css
  packages/dragdrop/tests/src/index.spec.ts
Labels: bug

#653 Remove dynamic keyboard event mode
  packages/application/src/index.ts
  review/api/application.api.md
Labels: enhancement, accessibility, deprecation

#644 adds isKeybinding arg to _executeKeyBinding
  packages/commands/src/index.ts
  packages/commands/tests/src/index.spec.ts
Labels: feature
