Repository jupyterlab/lumino, pull requests merged in 2023-07, with the labels that each got.

#546 Resize column to fit text on double click
  examples/example-datagrid/src/index.ts
  packages/datagrid/src/basicmousehandler.ts
  packages/datagrid/src/datagrid.ts
  packages/datagrid/src/hyperlinkrenderer.ts
  packages/datagrid/src/textrenderer.ts
  review/api/datagrid.api.md
Labels: enhancement

#606 Do not set the dockpanel as parent of the tabbar
  packages/widgets/src/docklayout.ts
  packages/widgets/tests/src/dockpanel.spec.ts
Labels: bug, feature

#590 elements respond to enter or spacebar
  packages/widgets/src/tabbar.ts
  packages/widgets/tests/src/tabbar.spec.ts
Labels: enhancement, accessibility

#612 [accessibility] Uses the arrow keys for tab bar navigation
  packages/widgets/src/tabbar.ts
  packages/widgets/tests/src/tabbar.spec.ts
  review/api/widgets.api.md
Labels: enhancement, accessibility

#619 Update versions
  buildutils/package.json
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
  yarn.lock
Labels: maintenance

#615 Added role of button to addButton to make itkeyboard accessible when using screenreader
  packages/widgets/src/tabbar.ts
Labels: bug, accessibility
