Repository jupyterlab/lumino, pull requests merged in 2023-06, with the labels that each got.

#592 Use Actual Return character for Mac shortcuts.
  packages/commands/src/index.ts
Labels: enhancement

#582 Splits with merge option for dock panels
  examples/example-dockpanel/src/index.ts
  packages/widgets/src/docklayout.ts
  packages/widgets/tests/src/docklayout.spec.ts
  review/api/widgets.api.md
Labels: enhancement

#588 Add a 'defer' option to the autoStart argument
  packages/application/src/index.ts
  packages/application/tests/src/index.spec.ts
  review/api/application.api.md
Labels: enhancement

#598 Upgrade releaser workflows
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/tests.yml
  package.json
Labels: maintenance

#600 Bump versions
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  packages/application/package.json
  packages/commands/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/dragdrop/package.json
  packages/widgets/package.json
  yarn.lock
Labels: maintenance

#602 Update releaser workflow names
  RELEASE.md
Labels: documentation
