Repository jupyterlab/lumino, pull requests merged in 2023-02, with the labels that each got.

#534 Remove cursor style
  packages/widgets/style/widget.css
Labels: bug

#531 Check for hidden items before re-rendering
  packages/widgets/src/commandpalette.ts
  review/api/widgets.api.md
Labels: enhancement, performance

#537 Accessibility in accordion panel
  packages/widgets/src/accordionlayout.ts
  packages/widgets/src/accordionpanel.ts
  packages/widgets/tests/src/accordionpanel.spec.ts
  review/api/widgets.api.md
Labels: bug, accessibility

#489 Collapse main menu options in a hamburger menu
  examples/example-dockpanel/src/index.ts
  packages/widgets/src/menubar.ts
  packages/widgets/tests/src/menubar.spec.ts
  review/api/widgets.api.md
Labels: enhancement

#536 Update to yarn 3
  .eslintignore
  .github/workflows/tests.yml
  .gitignore
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  buildutils/package.json
  docs/source/conf.py
  package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/keyboard/src/index.ts
  packages/messaging/package.json
  packages/messaging/src/index.ts
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
  packages/widgets/src/accordionpanel.ts
  packages/widgets/src/boxengine.ts
  packages/widgets/src/boxpanel.ts
  packages/widgets/src/panel.ts
  packages/widgets/src/splitpanel.ts
  packages/widgets/src/stackedpanel.ts
  packages/widgets/src/widget.ts
  typedoc.js
  yarn.lock
Labels: maintenance

#544 Bump verdaccio
  yarn.lock
Labels: maintenance

#545 Set publication to public
  buildutils/package.json
Labels: maintenance
