Repository jupyterlab/lumino, pull requests merged in 2023-05, with the labels that each got.

#578 Invalid unicode characters removed from datagrid (#456)
  packages/datagrid/src/textrenderer.ts
Labels: bug

#564 Fix dblclick events with Drag.overrideCursor active (#547)
  packages/dragdrop/src/index.ts
Labels: bug

#585 Seed tests for datagrid, test `TextRenderer/drawText`
  packages/datagrid/package.json
  packages/datagrid/tests/karma.conf.js
  packages/datagrid/tests/rollup.config.mjs
  packages/datagrid/tests/src/index.spec.ts
  packages/datagrid/tests/src/textrenderer.spec.ts
  packages/datagrid/tests/tsconfig.json
  yarn.lock
Labels: maintenance

#583 Added "tabindex=0" for sidebar accessibility
  packages/widgets/src/tabbar.ts
  review/api/widgets.api.md
Labels: enhancement, accessibility
