Repository jupyterlab/lumino, pull requests merged in 2023-01, with the labels that each got.

#506 Add contain strict for elements with fully managed layout
  packages/widgets/src/accordionlayout.ts
  packages/widgets/src/docklayout.ts
  packages/widgets/src/dockpanel.ts
  packages/widgets/src/layout.ts
  packages/widgets/src/splitlayout.ts
Labels: enhancement, performance

#502 Improve performance of drag & drop, esp. in Chrome
  packages/dragdrop/src/index.ts
  packages/dragdrop/style/index.css
  packages/dragdrop/tests/src/index.spec.ts
Labels: bug, performance

#509 Bump to 2.0.0-alpha.7
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel-amd/package.json
  examples/example-dockpanel-iife/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  examples/example-nested-dockpanel-amd/package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
  yarn.lock
Labels: maintenance

#511 Automated Changelog Entry for 2023.1.3-alpha.7 on main
  CHANGELOG.md
Labels: documentation

#501 Only add aria-hidden for `scale` mode
  packages/widgets/src/widget.ts
Labels: bug, accessibility

#515 Update versions to 2.0.0-beta.0
  buildutils/package.json
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel-amd/package.json
  examples/example-dockpanel-iife/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  examples/example-nested-dockpanel-amd/package.json
  package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: maintenance

#516 Automated Changelog Entry for 2023.1.13-beta.0 on main
  CHANGELOG.md
Labels: documentation

#519 Bump versions for 1.x
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-datastore/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  packages/application/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/widgets/package.json
Labels: maintenance

#520 Automated Changelog Entry for 2023.1.19 on 1.x
  CHANGELOG.md
Labels: documentation

#521 Add deprecation warning on Signal blocking feature
  packages/signaling/src/index.ts
Labels: bug

#523 Bump versions
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-datastore/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  packages/application/package.json
  packages/commands/package.json
  packages/datagrid/package.json
  packages/datastore/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/dragdrop/package.json
  packages/polling/package.json
  packages/signaling/package.json
  packages/widgets/package.json
Labels: maintenance

#522 Revert "Add blocking signal feature (#443)"
  packages/signaling/package.json
  packages/signaling/src/index.ts
  packages/signaling/tests/src/index.spec.ts
  review/api/signaling.api.md
Labels: maintenance

#524 Automated Changelog Entry for 2023.1.23 on 1.x
  CHANGELOG.md
Labels: documentation

#526 Bump to 2.0.0-beta.1
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  packages/application/package.json
  packages/commands/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/dragdrop/package.json
  packages/polling/package.json
  packages/signaling/package.json
  packages/widgets/package.json
Labels: maintenance

#527 Automated Changelog Entry for 2023.1.24-beta.1 on main
  CHANGELOG.md
Labels: documentation
