Repository jupyterlab/lumino, pull requests merged in 2024-04, with the labels that each got.

#637 Accept individual modifier keys as valid keybindings
  packages/application/src/index.ts
  packages/commands/src/index.ts
  packages/commands/tests/src/index.spec.ts
  review/api/application.api.md
  review/api/commands.api.md
Labels: enhancement

#696 Align typedoc config with JupyterLab
  .licenserc.yaml
  package.json
  packages/algorithm/package.json
  packages/algorithm/src/array.ts
  packages/algorithm/typedoc.json
  packages/application/package.json
  packages/application/typedoc.json
  packages/collections/package.json
  packages/collections/typedoc.json
  packages/commands/package.json
  packages/commands/typedoc.json
  packages/coreutils/package.json
  packages/coreutils/typedoc.json
  packages/datagrid/package.json
  packages/datagrid/typedoc.json
  packages/disposable/package.json
  packages/disposable/typedoc.json
  packages/domutils/package.json
  packages/domutils/typedoc.json
  packages/dragdrop/package.json
  packages/dragdrop/typedoc.json
  packages/keyboard/package.json
  packages/keyboard/src/index.ts
  packages/keyboard/typedoc.json
  packages/messaging/package.json
  packages/messaging/typedoc.json
  packages/polling/package.json
  packages/polling/typedoc.json
  packages/properties/package.json
  packages/properties/typedoc.json
  packages/signaling/package.json
  packages/signaling/typedoc.json
  packages/virtualdom/package.json
  packages/virtualdom/typedoc.json
  packages/widgets/package.json
  packages/widgets/src/accordionlayout.ts
  packages/widgets/src/singletonlayout.ts
  packages/widgets/typedoc.json
  tsconfig.docs.json
  typedoc-theme/partials/header.hbs
  typedoc.base.json
  typedoc.js
  yarn.lock
Labels: documentation

#695 Datagrid: Add a public API to get the current viewport
  packages/datagrid/src/datagrid.ts
  packages/datagrid/tests/src/datagrid.spec.ts
  packages/datagrid/tests/src/index.spec.ts
  review/api/datagrid.api.md
Labels: enhancement, api-change
