Repository jupyterlab/lumino, pull requests merged in 2025-03, with the labels that each got.

#743 "npm run" -> yarn
  .github/workflows/tests.yml
  package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
Labels: maintenance, javascript

#745 Forbid .only and .skip on CI
  packages/algorithm/web-test-runner.config.js
  packages/application/web-test-runner.config.js
  packages/collections/web-test-runner.config.js
  packages/commands/web-test-runner.config.js
  packages/coreutils/web-test-runner.config.js
  packages/datagrid/web-test-runner.config.js
  packages/default-theme/web-test-runner.config.js
  packages/disposable/web-test-runner.config.js
  packages/domutils/web-test-runner.config.js
  packages/dragdrop/web-test-runner.config.js
  packages/keyboard/web-test-runner.config.js
  packages/messaging/web-test-runner.config.js
  packages/polling/web-test-runner.config.js
  packages/properties/web-test-runner.config.js
  packages/signaling/web-test-runner.config.js
  packages/virtualdom/web-test-runner.config.js
  packages/widgets/tests/src/docklayout.spec.ts
  packages/widgets/tests/src/menu.spec.ts
  packages/widgets/web-test-runner.config.js
Labels: maintenance

#747 Remove use of `tj-actions/changed-files`
  .github/workflows/check-api-changes.yml
Labels: maintenance

#746 Don't refresh if palette is within a hidden branch
  buildutils/src/rollup.tests.config.js
  packages/widgets/src/commandpalette.ts
  packages/widgets/src/widget.ts
  packages/widgets/tests/src/commandpalette.spec.ts
  packages/widgets/tests/src/tabbar.spec.ts
  packages/widgets/tests/src/widget.spec.ts
  review/api/widgets.api.md
Labels: enhancement

#751 Update versions
  buildutils/package.json
  examples/example-accordionpanel/package.json
  examples/example-datagrid/package.json
  examples/example-dockpanel/package.json
  examples/example-menubar/package.json
  packages/algorithm/package.json
  packages/application/package.json
  packages/collections/package.json
  packages/commands/package.json
  packages/coreutils/package.json
  packages/datagrid/package.json
  packages/default-theme/package.json
  packages/disposable/package.json
  packages/domutils/package.json
  packages/dragdrop/package.json
  packages/keyboard/package.json
  packages/messaging/package.json
  packages/polling/package.json
  packages/properties/package.json
  packages/signaling/package.json
  packages/virtualdom/package.json
  packages/widgets/package.json
  yarn.lock
Labels: maintenance
